let
    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WSs4oLcqLTynNza1Uio0FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Column1", "churn_dummy"}})
in
    #"Renamed Columns"