let
    Source = #"public prod_churn",
    #"Removed Other Columns" = Table.SelectColumns(Source,{"tenure_in_months"}),
    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
    #"Added Custom" = Table.AddColumn(#"Removed Duplicates", "tenure_grp", each if [tenure_in_months] <7 then "< 7"
else if [tenure_in_months] <14 then "7-14"
else if [tenure_in_months] <21 then "14-21"
else if [tenure_in_months] <28 then "21-28"
else ">28"),
    #"Added Custom1" = Table.AddColumn(#"Added Custom", "tenure_group_sorting", each if [tenure_in_months] < 7 then "1"
else if [tenure_in_months] < 14 then "2"
else if [tenure_in_months] < 21 then "3"
else if [tenure_in_months] < 28 then "4"
else "5"),
    #"Changed Type" = Table.TransformColumnTypes(#"Added Custom1",{{"tenure_group_sorting", Int64.Type}})
in
    #"Changed Type"